// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp4uO09tKC0YMmuVZ_ndqg_Fd0th8EPSg',
    appId: '1:309782887849:web:c2a0b2d86b061e829198b8',
    messagingSenderId: '309782887849',
    projectId: 'hostelswap-af004',
    authDomain: 'hostelswap-af004.firebaseapp.com',
    storageBucket: 'hostelswap-af004.firebasestorage.app',
    measurementId: 'G-B78E54NLS6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqPqKVWnX_TuA16vkzpP25Q2GBhc7oOVQ',
    appId: '1:309782887849:android:2caf302c3aa300559198b8',
    messagingSenderId: '309782887849',
    projectId: 'hostelswap-af004',
    storageBucket: 'hostelswap-af004.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALM6mQ9MMTnwmaXaeh8MIsf4Se-dmEo98',
    appId: '1:309782887849:ios:b07488062201b3139198b8',
    messagingSenderId: '309782887849',
    projectId: 'hostelswap-af004',
    storageBucket: 'hostelswap-af004.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALM6mQ9MMTnwmaXaeh8MIsf4Se-dmEo98',
    appId: '1:309782887849:ios:b07488062201b3139198b8',
    messagingSenderId: '309782887849',
    projectId: 'hostelswap-af004',
    storageBucket: 'hostelswap-af004.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDp4uO09tKC0YMmuVZ_ndqg_Fd0th8EPSg',
    appId: '1:309782887849:web:a9ffa2ef81afab849198b8',
    messagingSenderId: '309782887849',
    projectId: 'hostelswap-af004',
    authDomain: 'hostelswap-af004.firebaseapp.com',
    storageBucket: 'hostelswap-af004.firebasestorage.app',
    measurementId: 'G-MLJE0M61CG',
  );
}
