REQUEST_STATUS_ACTIVE = "active"
REQUEST_STATUS_MATCHED = "matched"
REQUEST_STATUS_WITHDRAWN = "withdrawn"
REQUEST_STATUS_EXPIRED = "expired"

INTEREST_STATUS_PENDING = "pending"
INTEREST_STATUS_ACCEPTED = "accepted"
INTEREST_STATUS_REJECTED = "rejected"

GENDER_MALE = "male"
GENDER_FEMALE = "female"
GENDER_OTHER = "other"
ALL_GENDERS = {GENDER_MALE, GENDER_FEMALE, GENDER_OTHER}
